import type { Metadata } from "next";
import "./globals.css";
import '@fontsource-variable/playfair-display';
import { Analytics } from "@vercel/analytics/next"

export const metadata: Metadata = {
  title: "FacturePro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
