import NavbarDashboard from '@/components/layout/navigation/dashboard-navigation/NavbarDashboard';
import SidebarDashboard from '@/components/layout/navigation/dashboard-navigation/SidebarDashboard';
import { Metadata } from 'next';
import { Toaster } from 'sonner';
import { Analytics } from "@vercel/analytics/next"

interface DashboardLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: DashboardLayoutProps) {

  return (
    <body>
    <div className="flex h-screen bg-orange-100">
      <SidebarDashboard />
      <div className="flex flex-col flex-1 overflow-hidden">
        <NavbarDashboard />
        <main className="flex-1 overflow-y-auto">
          <div className="space-y-6">
            {children}
          </div>
          <Toaster />
        </main>
      </div>
    </div>
    <Analytics />
    </body>
  );
}